### PR TITLE
Changed how the background was drawn

### PR DESCRIPTION
**Pull request by amg1976**
Thanks for distributing this project, I was trying to achieve the same result but was going on a much more complicated solution!

In order to correctly support a border on the badge, I needed to refactor how the background was being drawn, because the end result wasn't correct, in my opinion.
screen shot 2015-11-28 at 11 42 11 a m
So instead of setting the background color on the layer to the desired color, the layer is now always clearColor and a UIBezierPath is used instead, with fill color based on the UILabel background color. This way, if the value of borderWidth is set to a value bigger than 0, it will set the stroke color and line width of the UIBezierPath.

### CODE REVIEW

**Comment by evgenyneu** [comment]
Hi, @amg1976. Thank you for the update, the border can be useful to people. There are three things that need to be done before I can merge it:
- [ ] Fix text alignment for single character text, as shown in the image below. The text needs to be centred instead of being left-aligned.
- [ ] Add example on how to set the border width and colour to the README. 
- [ ] It would be nice to add a screenshot with bordered badge to the README as well, in addition to the borderless one.

swift-badge-text-align

**Comment by lastmboy** [comment]
Do you know if this change would also fix the problem when the badge is used on a UITableView row? Currently, if you select the row (highlight), the background of the badge disappears.

**Comment by amg1976** [comment]
@lastmboy it doesn't fix that issue. In a simple test I made, if SwiftBadge overrides the `var highlighted: Bool` property and always return `yes`, the background color is correctly drawn. But this needs to be tested further.

**Comment by evgenyneu** [comment]
Thank you very much for your contribution, @amg1976.

**Comment by evgenyneu** [comment]
@lastmboy I added a test to the demo app in this project that shows badges in a table view. I could not reproduce your problem when a row is selected. Feel free to get the new version of the Badge, give it a go and let me know if the issue still exists. Thanks.

badge_table_view_selected

**Pull request merged**
